Add reattach feature to the clean-net.
New --reattach feature allows one to set different interface for
specific network namespace (--name).

For example to reattach from wlan0 to eth0 in vpn3 NS:

root$ clean-net --reattach eth0 --name vpn3

diff --git a/clean-net b/clean-net
--- a/clean-net
+++ b/clean-net
@@ -4,13 +4,14 @@
 help()
 {
     cat <<EOF
-$0 -- remove network namespace and cleanup iptables -t nat rule added by build-net.sh
+${0##*/} -- remove network namespace and cleanup iptables -t nat rule added by build-net.sh
 
-Usage: $0 [options]
+Usage: ${0##*/} [options]
 
 Options:
   -h | --help              print this help message
   -n | --name              namespace name
+  -r | --reattach          reattach to namespace to another interface
   -f | --disable-forward   disable IPv4 forwarding
 EOF
     exit 0
@@ -24,7 +25,7 @@ before_exit()
 [ $# -ge 1 ] || help
 
 # Parse command line arguments
-TMPARGS="$(getopt -n "$0" -o n:,f,h -l name:,disable-forward,help -- "$@")" ||
+TMPARGS="$(getopt -n "$0" -o n:,f,r:,h -l name:,disable-forward,reattach:,help -- "$@")" ||
 	  help
 eval set -- "$TMPARGS"
 
@@ -38,6 +39,8 @@ do
             shift; NS="$1" ;;
         -f|--disable-forward)
             shift; DISABLE_FORWARD=1; break ;;
+        -r|--reattach)
+            shift; REATTACH="$1" ;;
         *)
             help ;;
     esac
@@ -45,48 +48,61 @@ do
 done
 
 # Check PIDs
-pids="$(ip netns pids "$NS")"
-if [ "$(ip netns pids "$NS")" != "" ]
-then
-    echo -ne "WARNING: $NS has follwing PIDs:\n$pids\n"
-    echo -ne "Do you want to kill automatically or manually?\n(a/m) > "
-    read KILL
-    if [ "$KILL" = "a" ]
+if [ -z "${REATTACH-}" ]; then
+    pids="$(ip netns pids "$NS")"
+    if [ "$(ip netns pids "$NS")" != "" ]
     then
-        for i in $pids
-        do
-            kill "$i" || continue
-            while [ -e "/proc/$i" ]
-            do
-                sleep 1
-                echo "Waiting for $i..."
-            done
-        done
-
-        if [ "$(ip netns pids "$NS")" != "" ]
+        echo -ne "WARNING: $NS has follwing PIDs:\n$pids\n"
+        echo -ne "Do you want to kill automatically or manually?\n(a/m) > "
+        read KILL
+        if [ "$KILL" = "a" ]
         then
-            echo "Can't kill all PIDs. Exit."
-            exit 1
+            for i in $pids
+            do
+                kill "$i" || continue
+                while [ -e "/proc/$i" ]
+                do
+                    sleep 1
+                    echo "Waiting for $i..."
+                done
+            done
+
+            if [ "$(ip netns pids "$NS")" != "" ]
+            then
+                echo "Can't kill all PIDs. Exit."
+                exit 1
+            fi
+        else
+            exit 0
         fi
-    else
-        exit 0
     fi
 fi
 
-trap before_exit EXIT HUP PIPE INT QUIT TERM
-
-# Get ip route
-IPT=$(ip -netns "$NS" route | awk '/^172\.24.*eth0/{print $1}')
-# Delete iptables rule and network namespace
+# Get ip route and veth pair
+IPT="$(ip -netns "$NS" route | awk '/^172\.24.*eth0/{print $1}')"
 VPND="$(ip -human -oneline -details link | awk "/link-netns $NS/{match(\$0, /^[0-9]+:[ ]*([^ ]*)@if/, m); print m[1]}")"
 INT="$(iptables -S | awk "/.*-o ${VPND}.*/{if(match(\$0, /.*-i ([^ ]+) .*/, m)){print m[1]}}")"
-iptables -D FORWARD -i "$VPND" -o "$INT" -j ACCEPT
-iptables -D FORWARD -o "$VPND" -i "$INT" -j ACCEPT
-iptables -t nat -D POSTROUTING -s "$IPT" -o "$INT" -j MASQUERADE
-ip route del "$IPT"
-ip link del "$VPND"
 
-# Delete resolv.conf setup
-[ ! -d "/etc/netns/$NS" ] || rm -rf "/etc/netns/$NS"
-# Disable IPv4 forward
-[ -z "${DISABLE_FORWARD-}" ] || echo "0" > /proc/sys/net/ipv4/ip_forward
+# Find rulenum in case of reattach mode or delete rules
+if [ -n "${REATTACH-}" ]; then
+    RULENUM="$(iptables -S FORWARD | grep '^-[^P].*' | awk "/-A FORWARD -i $INT -o $VPND -j ACCEPT/{print NR}")"
+    iptables -R FORWARD "$RULENUM" -i "$REATTACH" -o "$VPND" -j ACCEPT
+    RULENUM="$(iptables -S FORWARD | grep '^-[^P].*' | awk "/-A FORWARD -i $VPND -o $INT -j ACCEPT/{print NR}")"
+    iptables -R FORWARD "$RULENUM" -i "$VPND" -o "$REATTACH" -j ACCEPT
+    RULENUM="$(iptables -t nat -S POSTROUTING | grep '^-[^P].*' | awk "/-A POSTROUTING -s ${IPT/\//\\/} -o $INT -j MASQUERADE/{print NR}")"
+    iptables -t nat -R POSTROUTING "$RULENUM" -s "$IPT" -o "$REATTACH" -j MASQUERADE
+else
+    trap before_exit EXIT HUP PIPE INT QUIT TERM
+
+    # Delete iptables rule and network namespace
+    iptables -D FORWARD -i "$VPND" -o "$INT" -j ACCEPT
+    iptables -D FORWARD -o "$VPND" -i "$INT" -j ACCEPT
+    iptables -t nat -D POSTROUTING -s "$IPT" -o "$INT" -j MASQUERADE
+    ip route del "$IPT"
+    ip link del "$VPND"
+
+    # Delete resolv.conf setup
+    [ ! -d "/etc/netns/$NS" ] || rm -rf "/etc/netns/$NS"
+    # Disable IPv4 forward
+    [ -z "${DISABLE_FORWARD-}" ] || echo "0" > /proc/sys/net/ipv4/ip_forward
+fi
